# -*- coding: utf-8 -*-
"""day1_data engineering .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-l1WvVhZ5oruhy2veTwabi1e5czxABY

https://drive.google.com/drive/folders/1ynXC2BT7s7NgOzMKt4dtYjspEj3bu6Ao
"""

#Step 1 import the pandas
import pandas as pd
#imported the pandas as pd
#Now we are printing the msg
print("Imported the pandas library successfully")

df=pd.read_csv("student_performance.csv")
#used to load the dataset

print("Successfully loaded the file")

df.head()
#Used to print the first five data from the dataset

df.tail()
#Used to print the last five data from the dataset
#used to indentify the duplicate rows
#when we are having 100 rows in the dataset
#but tail shows only from 46 to 50 rows than what it means only 50 rows are identical and without duplicate

print("Shape of dataset:",df.shape)

print("Number of statement",df.shape[0])

print("Number of columns",df.shape[1])

print("Data Types")
print(df.dtypes)
#it is udes to give the types data stored column wise
#In Python string -> object in pandas

df.describe()
#it is used to print the count, mean value....

print("Missing values in each column:")
print(df.isnull().sum())
#it is used to print the missing values in each column

print("Student names:")
print(df['name'])

print("Department in the dataset:")
print(df['department'].unique())

print("\n how many students per department")
print(df['department'].value_counts())

cs_Students=df[df['department']=='Computer Science']
print(f"Number of students in cs department:",len(cs_Students))

high_attendance=df[df['attendance_percentage']>90]
print("Student with high attendance:",len(high_attendance))
print(high_attendance)

df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

dept_avg=df.groupby('department')['total_score'].mean().round(2)
print("Avg total score by department:")
print(dept_avg)

df_sorted=df.sort_values(by='total_score',ascending=False)
print("Top 20 students based on total score:")
print(df_sorted.head(20))

"""Question
1. How many students are from electronic department?
2. What is the averaage attendance of the female students?
3. who is the student with the lowest programming score?
4. how many students score above 80 in math?
5. What is the average total score for students with attendance above 90 percentage?




"""

#1.How many students are from electronic department?
electronics_Students=df[df['department']=='Electronics']
print(f"Number of students in electronics department:",len(electronics_Students))

#2.What is the averaage attendance of the female students?
female_students=df[df['gender']=='Female']
avg_attendance=female_students['attendance_percentage'].mean()
print(f"Average attendance of female students:",avg_attendance)

#3.who is the student with the lowest programming score?
lowest=df[df['programming_score']==df['programming_score'].min()]
print(lowest['name'])

#4.how many students score above 80 in math?
math=df[df['math_score']>80]
print(f"Number of students with math score above 80:",len(math))

#5.What is the average total score for students with attendance above 90 percentage?
avg=df[df['attendance_percentage']>90]
avg_total=avg['total_score'].mean()
print(f"Average total score for students with attendance above 90 percentage:",avg_total)

"""# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings
"""

print("=" * 40)
print("      Student Performance Explorer")
print("=" * 40)
print()
print("=" * 40)
print("Data Set Overview")
print("=" * 40)
print("Total Number of Students:",len(df))
print("Total Number of columns: ",df.shape[1])
print("nummber of unique department: ",df['department'].nunique())
print("Department wise analysis")
print(df['department'].value_counts())
print()
print("=" * 40)
print("Score Analysis")
print("=" * 40)
print()
print("Highest math mark:",df['math_score'].max())
print("Lowest math mark:",df['math_score'].min())
print("Average math mark:",df['math_score'].mean())
print("Average programming mark:",df['programming_score'].mean())
print("Average attendance mark:",df['attendance_percentage'].mean())
print()
print("=" * 40)
print("Gender wise Analysis")
print("=" * 40)
female=df[df['gender']=='Female']
male=df[df['gender']=='Male']
print("Average total score by gender:")
print("Female:",female['total_score'].mean())
print("Male:",male['total_score'].mean())
print()
print("=" * 40)
print("Top performers")
print("=" * 40)
top_students=df.sort_values(by='total_score',ascending=False)
print("Top 5 students based on total score:")
top=top_students.head(5)
print("name: ",top['name'])
print("department:" ,top['department'])
print("total score:",top['total_score'])
print()
print("=" * 40)
print("Attendance Analysis")
print("=" * 40)
below_75=df[df['attendance_percentage']<75]
if len(below_75)==0:
    print("All students have attendance above 75%")
else:
    print(below_75[['name','department','attendance_percentage']])