# -*- coding: utf-8 -*-
"""day2_Data_Engineering_Database_sql_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-7YeLoJQx9-gKt5fBeMAGivYA5iJy1d
"""

import sqlite3
#import this to use the sql commands
import pandas as pd
#it is udes to load the excel data do some action on it
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
#it is used to ignore the samll warnings

print("All libraries are imorted successfully")
print(f"pandas version :{pd.__version__}")
print(f"sqlite3 version :{sqlite3.version}")

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("student_performance.csv")

print("Database loaded: ",df.shape[0],"Students:",df.shape[1],"Columns")
print(f"Cloumns: {df.columns.tolist()}")
print("\nFirst 5 rows ")
df.head()

import sqlite3

try:
    conn.close()
except:
    pass

conn = sqlite3.connect("college.db")
cursor = conn.cursor()

conn=sqlite3.connect("college.db")
#if college db is not exist than it will create the db
cursor= conn.cursor()
#cursor is like a pen that wrrite SQL Commands into the database
#Every SQL query goes through the cursor
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)
# to_sql() automatically
#1.create the table name with which conn if it is already table exited than replace as this and remove index
cursor.execute("SELECT count(*) from students")
count=cursor.fetchone()[0]
print("College db created successfully")
print(f"Table Student has {count} rows")

cursor.execute("PRAGMA Table_info(students)")
#pragma is used give the structure of the table it is not standard command in sql but we use it in sqlite
column_info=cursor.fetchall()
#fectall() retrive all rows

print("Table structure of 'students':")
print(f"{'column Name':<25}{'Data type':<12}")
#:<25 for proper alginment also :<12 this too
print("-"*30)
for col in column_info:
    print(f"{col[1]:<25}{col[2]:<12}")

def run_query(sql,description=""):
  if description:
    print(f"\n{'='*55}")
    print(f" {description}")
    print(f"{'='*55}")
  result=pd.read_sql(sql,conn)
  print(result.to_string(index=False))
  return result
print("")

"""1. find total umber of students.
2. Display all data types and column name using pragma.
3. Show first 5 rows from the students table.
4. Display Students with math mark > 80

"""

#Show first 5 rows from the students table.
cursor.execute("SELECT * FROM students LIMIT 5")
for row in cursor.fetchall():
    print(row)

#Display Students with math mark > 80
cursor.execute("SELECT name FROM students WHERE math_score > 80")
for row in cursor.fetchall():
    print(row)

query="select * from students limit 5"
run_query(query,"list of the first 5 students")

query1= "select name,department,math_score from students order by math_score desc limit 5"
run_query(query1,"Top 5 students based on their math score")
#run_query is the def function

query2="select name,math_score,science_score,programming_score,attendance_percentage as atttendance from students where department='Computer Science' order by programming_score desc limit 5"
run_query(query2,"top 5 prgrammers in computer science department")

query3="select name, department,attendance_percentage from students where attendance_percentage >90 AND department!='civil' order by attendance_percentage desc"
run_query(query3,"students with high attendance except civil department")

query4="select department, count(*),round(avg(math_score),2)as avg_math,round(avg(science_score),2)as avg_science,round(avg(programming_score))as avg_peogramming,round(avg(attendance_percentage))as avg_attendance from students group by department "
run_query(query4,"department wise average")

query5="Select department,round(avg(math_score),2)as avg_math,count(*)as students from students group by department having avg_math>70 order by avg_math desc"
run_query(query5,"department wise average math score greater than 70")

query6="select gender, count(*)as no_stud,round(avg(math_score),2)as avg_math,round(avg(attendance_percentage),2)as avg_attendance from students group by gender"
run_query(query6,"gender wise average")

query7="select name, department, math_score+science_score+programming_score as total_score from students order by total_score desc limit 5"
run_query(query7,"top 5 students based on total score")

dept_data={
    'dept_code': ['cs','ec','me','ce'],
    'dept_name': ['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name': ['Dr. suba','Dr. rama','Dr. ravi','Dr. kumar'],
    'establishied_year': [2000,2001,2002,2003],
    'intake' : [60,50,80,90]
}
dept_df=pd.DataFrame(dept_data)
dept_df.to_sql('departments',conn,if_exists='replace',index=False)
print("created department table")
print(dept_df.to_string(index=False))
dept_map={
    'Computer Science':'cs',
    'Electronics':'ec',
    'Mechanical':'me',
    'Civil':'ce'
}
df['dept_code']=df['department'].map(dept_map)
df.head()

query_join = "SELECT s.name,s.math_score,d.dept_name,d.hod_name,d.establishied_year FROM students AS s INNER JOIN departments AS d ON s.department = d.dept_name ORDER BY s.math_score DESC limit 8"
result_join = run_query(query_join, "JOIN: Students with Department Details (INNER JOIN)")

# Step 1: Get data using SQL
chart1_sql = "SELECT department, ROUND(AVG(math_score),1) AS avg_math FROM students GROUP BY department ORDER BY avg_math DESC"
chart1_data = pd.read_sql_query(chart1_sql, conn)
# Step 2: Create the bar chart
fig, ax = plt.subplots(figsize=(10, 6))
# fig = the whole figure (canvas)
# ax = the axes object (the actual plot area)
# figsize=(10, 6) = 10 inches wide, 6 inches tall

bar_colors = ['#4FC3F7', '#00897B', '#E67E22', '#8E44AD']
# List of hex color codes - one color per department bar
# Same color palette as our PPT slides for consistency

bars = ax.bar(
chart1_data['department'],
chart1_data['avg_math'],
color=bar_colors,
edgecolor='white',
linewidth=0.8
)
# x-axis values (category labels)
# y-axis values (heights of bars)
# colors for each bar
# white border around each bar
# thickness of the border
# Add value labels ON TOP of each bar
for bar in bars:
   height = bar.get_height()
# .get_height() returns the bar's height (= the avg_math value)
   ax.text(
      bar.get_x() + bar.get_width() / 2, # x position: center of bar
      height + 0.8,
      f'{height : 1f}',
      ha='center', va='bottom',
      fontsize=12, fontweight='bold',
)
# y position: just above bar top
# text: height formatted to 1 decimal
# horizontal/vertical alignment
ax.set_title('Average Math Score by Department', fontsize=16, fontweight='bold', pad=15)
ax.set_xlabel('Department', fontsize=13)
ax.set_ylabel('Average Math Score', fontsize=13)
ax.set_ylim(0, 105) # y-axis from 0 to 105 so labels above bars fit
ax.tick_params(axis='x', labelsize=11)
# axis='y' adds horizontal gridlines only
# alpha=0.3 makes gridlines 70% transparent
# linestyle=' -- ' makes them dashed

plt.tight_layout()
plt.show()


# Adjusts spacing to prevent label clipping
# Displays the chart

# Get programming scores as a list
prog_scores = df['programming_score'].tolist()
# .tolist() converts a Pandas Series to a regular Python list
# Matplotlib's hist() works with both - tolist() is just explicit

fig, ax = plt.subplots(figsize=(10, 6))

n, bins, patches = ax.hist(
    prog_scores,
    bins=8,
    color='#4FC3F7',
    edgecolor='white',
    linewidth=0.8,
    alpha=0.85
)
# The data to visualize
# Divide score range into 8 equal intervals
# Bar fill color
# White border between bars

# Slight transparency
# Add a vertical line showing the mean score
mean_score = sum(prog_scores) / len(prog_scores)
ax.axvline(
    x=mean_score,
    color='#E74C3C',
    linestyle='--',
    linewidth=2,
    label=f'Mean: {mean_score:.1f}' # label for the legend
)
# axvline = 'axis vertical line' - draws a vertical reference line

ax.set_title('Distribution of Programming Scores', fontsize=16, fontweight='bold', pad=15)
ax.set_xlabel('Programming Score', fontsize=13)
ax.set_ylabel('Number of Students', fontsize=13)
ax.legend(fontsize=12) # Shows the mean line label
ax.grid(axis='y', alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

# x position of the vertical line
# red color for visibility
# dashed line style

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Sample dataset (replace with your own CSV)
df = pd.DataFrame({
'Category': np.random.choice(['A','B','c','D'], 100),
'Value': np.random.randint(10, 100, 100),
'Score': np.random.randint(1, 10, 100)
})

df.head()

import plotly.io as pio
pio.renderers.default = 'notebook'

import plotly.express as px

category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']

fig = px.bar(
      category_counts,
      x='Category',
      y='Count',
      color='Category',
      title='Interactive Category Distribution',
      text='Count'
)
fig.update_traces(textposition='outside')
fig.update_layout(xaxis_title='Category', yaxis_title='Count')
fig.show()

"""MINI PROJECT: Student Performance Dashboard

Goal: Build a complete, professional dashboard using SQL + Matplotlib.

Combine 4 charts into a single figure using plt.subplots(2, 2) - a 2×2 grid.

avg total score department wise -> barchart

studets department wise -> pie chart

top 8 student total score->horizontal bar chart

gender wise attendance percentage-> barchart

"""

import matplotlib.pyplot as plt
import pandas as pd

fig, axs = plt.subplots(2, 2, figsize=(14, 8))

# ---------------- Chart 1 ----------------
ch1 = """
SELECT department,
ROUND(AVG(math_score),2) as avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC
"""
ch1_data = pd.read_sql_query(ch1, conn)

bars = axs[0,0].bar(
    ch1_data['department'],
    ch1_data['avg_math'],
    color='#4FC3F7',
    edgecolor='white'
)

for bar in bars:
    height = bar.get_height()
    axs[0,0].text(
        bar.get_x() + bar.get_width()/2,
        height + 0.5,
        f'{height:.1f}',
        ha='center'
    )

axs[0,0].set_title('Average Math Score by Department')
axs[0,0].set_xlabel('Department')
axs[0,0].set_ylabel('Average Math Score')

# ---------------- Chart 2 ----------------
ch2 = """
SELECT department,
COUNT(*) as num_students
FROM students
GROUP BY department
"""
ch2_data = pd.read_sql_query(ch2, conn)

axs[0,1].pie(
    ch2_data['num_students'],
    labels=ch2_data['department'],
    autopct='%1.1f%%'
)

axs[0,1].set_title('Department Distribution')

# ---------------- Chart 3 ----------------
ch3 = """
SELECT name,
math_score + science_score + programming_score as total_score
FROM students
ORDER BY total_score DESC
LIMIT 8
"""
ch3_data = pd.read_sql_query(ch3, conn)

bars=axs[1,0].barh(
    ch3_data['name'],
    ch3_data['total_score'],
    color='#4FC3F7',
    edgecolor='white'
)
for bar in bars:
    width = bar.get_width()
    axs[1,0].text(
        width + 0.5,
        bar.get_y() + bar.get_height()/2,
        f'{width:.1f}',
        ha='left'
    )

axs[1,0].set_title('Top 8 Students by Total Score')
axs[1,0].set_xlabel('Total Score')
axs[1,0].set_ylabel('Student Name')

# ---------------- Chart 4 ----------------
ch4 = """
SELECT gender,
ROUND(AVG(attendance_percentage)) as avg_attendance
FROM students
GROUP BY gender
"""
ch4_data = pd.read_sql_query(ch4, conn)

bars = axs[1,1].bar(
    ch4_data['gender'],
    ch4_data['avg_attendance'],
    color='#4FC3F7',
    edgecolor='white'
)

for bar in bars:
    height = bar.get_height()
    axs[1,1].text(
        bar.get_x() + bar.get_width()/2,
        height + 0.5,
        f'{height:.1f}',
        ha='center'
    )

axs[1,1].set_title('Average Attendance by Gender')
axs[1,1].set_xlabel('Gender')
axs[1,1].set_ylabel('Attendance %')

# Adjust layout
plt.tight_layout()

# Show all charts
plt.show()