# -*- coding: utf-8 -*-
"""day4_ml_spark-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBVn8jDjZxty5Wl3L-73VztBy5AqCDjF
"""

import pandas as pd

a = pd.read_csv("SOCR-HeightWeight.csv")
print("Loaded the dataset Successfully")

a.head()

a.tail()

a.isnull().sum()

a.isnull().any()

from sklearn.model_selection import train_test_split
x=a[['Height(Inches)']]
y=a[['Weight(Pounds)']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

x_train

from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

y_predict=model.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

mean_absolute_error(y_test,y_predict)

mean_squared_error(y_test,y_predict)

r2_score(y_test,y_predict)

import joblib

joblib.dump(model,"linear.pkl")