# -*- coding: utf-8 -*-
"""day4_ml_pyspark-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Cqmr_wcCIvHhb96G8TjIFJLDs2aAzzT
"""

import joblib

a=joblib.load("linear.pkl")

a.predict([[100]])

!pip install pyspark --quiet
print("pyspark installed")

from pyspark.sql import SparkSession
from pyspark.sql import functions as functions
from pyspark.sql.functions import year,month,to_date,col,round as spark_round
import matplotlib.pyplot as plt

import pandas as pd
import warnings
warnings.filterwarnings("ignore")
spark=SparkSession.builder \
.appName("Day4_BigData_Sales")\
.config("spark.sql.adaptive.enabled","true")\
.getOrCreate()

print("Spark version:",spark.version)[]
print(f"Spark session:Active")
print(f"Application:{spark.sparkContext.appName}")

df_bronze=spark.read \
.option('header','true')\
.option('inferSchema','true')\
.csv("large_sales_data.csv")
print("===BRONZE LAYER -- RAW DATA")
print(f"Rows :{df_bronze.count()}")
print(f"Columns :{len(df_bronze.columns)}")

print("First 5 rows:")
df_bronze.show(5,truncate=False)
print("\n Basic statistics for numeric columns:")
df_bronze.select('quantity','unit_price','revenue').describe().show()

df_bronze.write\
.mode('overwrite')\
.parquet('sales_bronze.parquet')
print('Bronze parquet saved:sales_bonze.parquet')

import os

a=pd.read_csv("data.csv")
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x=a[['bedrooms','sqft_living','yr_built']]
y=a[['price']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print(mean_absolute_error(y_test,y_predict))
print(mean_squared_error(y_test,y_predict))
r2_score(y_test,y_predict)
import joblib
joblib.dump(model,"linear2.pkl")
b=joblib.load("linear2.pkl")
b.predict([[3,1500,1998]])