# -*- coding: utf-8 -*-
"""day5_ML_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ld5ixAa9OlF0368-aPupa3uqHaXrnDY3
"""

a=pd.read_csv("data.csv")
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x=a[['bedrooms','sqft_living','yr_built']]
y=a[['price']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print(mean_absolute_error(y_test,y_predict))
print(mean_squared_error(y_test,y_predict))
print("r2:",r2_score(y_test,y_predict))
import joblib
joblib.dump(model,"linear2.pkl")
b=joblib.load("linear2.pkl")
b.predict([[3,1500,1998]])

import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

a=pd.read_csv("data.csv")

dt_model = DecisionTreeRegressor(
    max_leaf_nodes=5,
    random_state=42
)
x = a[['bedrooms', 'sqft_living', 'yr_built']]
y = a['price']
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)
dt_model.fit(x_train, y_train)

y_predict = dt_model.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print("MAE:", mean_absolute_error(y_test, y_predict))
print("MSE:", mean_squared_error(y_test, y_predict))
print("R2 Score:", r2_score(y_test, y_predict))

import joblib
joblib.dump(dt_model, "decision_tree.pkl")

b = joblib.load("decision_tree.pkl")
prediction_input = pd.DataFrame([[3, 1400, 1999]], columns=x.columns)
prediction = b.predict(prediction_input)
print("Predicted Price:", prediction[0])

dt_model1 = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)
x = a[['bedrooms', 'sqft_living', 'yr_built']]
y = a['price']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

dt_model1.fit(x_train, y_train)

y_predict = dt_model1.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_predict))
print("MSE:", mean_squared_error(y_test, y_predict))
print("R2 Score:", r2_score(y_test, y_predict))

import joblib
joblib.dump(dt_model1, "random_forest.pkl")
b = joblib.load("random_forest.pkl")
prediction_input = pd.DataFrame([[3, 1400, 1999]], columns=x.columns)
prediction = b.predict(prediction_input)
print("Predicted Price:", prediction[0])